SUMMARY = "WebKitBrowser plugin"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://../LICENSE;md5=16cf2209d4e903e4d5dcd75089d7dfe2"

# keep PV/PR in sync with meta-middleware-generic-support/conf/include/generic-pkgrev.inc
PV ?= "1.1.30"
PR ?= "r0"
PATCHTOOL = "git"

PACKAGE_ARCH = "${MIDDLEWARE_ARCH}"
S = "${WORKDIR}/git/WebKitBrowser"

SRC_URI = "git://github.com/rdkcentral/rdkservices.git;protocol=git;branch=main \
  file://0001-RDKTV-177-Configure-wpeframework-plugin-startup-orde.patch;patchdir=../ \
  file://0003-Increase-browser-creation-timeout.patch;patchdir=../ \
  file://0004-Reduce-BrowserConsoleLog.patch;patchdir=../ \
  file://0005-Enable-mixed-content.patch;patchdir=../ \
  file://0006-Introduce-state-aware-memory-observer.patch;patchdir=../ \
  file://0007-Legacy-launch-metrics.patch;patchdir=../ \
  file://0008-Thunder-upgrade-quirks.patch;patchdir=../ \
  file://0009-Thunder-R4.4.3-upgrade-Fix.patch;patchdir=../ \
"

# Tip of the main at June 27, 2025
SRCREV = "857eff8cdcf0a3506683043d0676d541e48dfaa3"

inherit cmake pkgconfig python3native

TOOLCHAIN = "gcc"

DEPENDS += "wpeframework wpeframework-tools-native ${WPEWEBKIT}"
DEPENDS += "${@bb.utils.contains('DISTRO_FEATURES', 'enable_libsoup3', 'libsoup', 'libsoup-2.4', d)}"
RRECOMMENDS:${PN} += "webkitbrowser-cache-cleanup"

PACKAGECONFIG ??= "residentapp searchanddiscoveryapp htmlapp lightningapp aampjsbindings badgerbridge customprocessinfo"

PACKAGECONFIG:append = " ${@bb.utils.contains("DISTRO_FEATURES", "jspp", "jspp","",d)}"

PACKAGECONFIG[debug]                 = "-DCMAKE_BUILD_TYPE=Debug,-DCMAKE_BUILD_TYPE=Release,"
PACKAGECONFIG[residentapp]           = "-DPLUGIN_WEBKITBROWSER_RESIDENT_APP=ON,-DPLUGIN_WEBKITBROWSER_RESIDENT_APP=OFF,"
PACKAGECONFIG[searchanddiscoveryapp] = "-DPLUGIN_WEBKITBROWSER_SEARCH_AND_DISCOVERY_APP=ON,-DPLUGIN_WEBKITBROWSER_SEARCH_AND_DISCOVERY_APP=OFF,"
PACKAGECONFIG[htmlapp]               = "-DPLUGIN_WEBKITBROWSER_HTML_APP=ON,-DPLUGIN_WEBKITBROWSER_HTML_APP=OFF,"
PACKAGECONFIG[lightningapp]          = "-DPLUGIN_WEBKITBROWSER_LIGHTNING_APP=ON,-DPLUGIN_WEBKITBROWSER_LIGHTNING_APP=OFF,"
PACKAGECONFIG[jspp]                  = "-DPLUGIN_WEBKITBROWSER_JSPP=ON,-DPLUGIN_WEBKITBROWSER_JSPP=OFF,"
PACKAGECONFIG[aampjsbindings]        = "-DPLUGIN_WEBKITBROWSER_AAMP_JSBINDINGS=ON,-DPLUGIN_WEBKITBROWSER_AAMP_JSBINDINGS=OFF,aamp"
PACKAGECONFIG[badgerbridge]          = "-DPLUGIN_WEBKITBROWSER_BADGER_BRIDGE=ON,-DPLUGIN_WEBKITBROWSER_BADGER_BRIDGE=OFF,"
PACKAGECONFIG[tzupdate]              = "-DPLUGIN_WEBKITBROWSER_UPDATE_TZ_FROM_FILE=ON,-DPLUGIN_WEBKITBROWSER_UPDATE_TZ_FROM_FILE=OFF,"
PACKAGECONFIG[customprocessinfo]     = "-DPLUGIN_WEBKITBROWSER_CUSTOM_PROCESS_INFO=ON,-DPLUGIN_WEBKITBROWSER_CUSTOM_PROCESS_INFO=OFF,"

BROWSER_MEMORYPROFILE ?= "default"

require include/webkitbrowser_properties.inc
require include/webkitbrowser_memorylimits.${BROWSER_MEMORYPROFILE}.inc

EXTRA_OECMAKE += " \
    -DCMAKE_SYSROOT=${STAGING_DIR_HOST} \
    -DBUILD_REFERENCE=${SRCREV} \
    -DBUILD_SHARED_LIBS=ON \
    -DPLUGIN_WEBKITBROWSER=ON \
    -DPLUGIN_WEBKITBROWSER_TESTING=OFF \
    -DPLUGIN_WEBKITBROWSER_TESTING_USE_WESTEROS=OFF \
    -DPLUGIN_WEBKITBROWSER_LOGGING_UTILS=ON \
    -DPLUGIN_WEBKITBROWSER_AUTOSTART="${WEBKITBROWSER_AUTOSTART}" \
    -DPLUGIN_WEBKITBROWSER_MEDIADISKCACHE="${WEBKITBROWSER_MEDIADISKCACHE}" \
    -DPLUGIN_WEBKITBROWSER_MEMORYPRESSURE_WEBPROCESS_SETTINGS_LIMIT="${WEBKITBROWSER_MEMORYPRESSURE_WEBPROCESSLIMIT}" \
    -DPLUGIN_WEBKITBROWSER_MEMORYPRESSURE_NETWORKPROCESS_SETTINGS_LIMIT="${WEBKITBROWSER_MEMORYPRESSURE_NETWORKPROCESSLIMIT}" \
    -DPLUGIN_WEBKITBROWSER_MEMORYPROFILE="${WEBKITBROWSER_MEMORYPROFILE}" \
    -DPLUGIN_WEBKITBROWSER_MSEBUFFERS="${WEBKITBROWSER_MSEBUFFERS}" \
    -DPLUGIN_WEBKITBROWSER_STARTURL="${WEBKITBROWSER_STARTURL}" \
    -DPLUGIN_WEBKITBROWSER_DISKCACHE="${WEBKITBROWSER_DISKCACHE}" \
    -DPLUGIN_WEBKITBROWSER_XHRCACHE="${WEBKITBROWSER_XHRCACHE}" \
    -DPLUGIN_WEBKITBROWSER_TRANSPARENT="${WEBKITBROWSER_TRANSPARENT}" \
    -DPLUGIN_WEBKITBROWSER_INJECTEBLE_BUNDLE="${WEBKITBROWSER_INJECTEBLE_BUNDLE}" \
    -DPLUGIN_WEBKITBROWSER_THREADEDPAINTING="${WEBKITBROWSER_THREADEDPAINTING}" \
    -DPLUGIN_HTML_APP_LOCALSTORAGESIZE="${HTML_APP_LOCALSTORAGESIZE}" \
    -DPLUGIN_LIGHTNING_APP_LOCALSTORAGESIZE="${LIGHTNING_APP_LOCALSTORAGESIZE}" \
    -DPLUGIN_JSPP_LOCALSTORAGESIZE="${JSPP_LOCALSTORAGESIZE}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_LOCALSTORAGESIZE="${SEARCH_AND_DISCOVERY_APP_LOCALSTORAGESIZE}" \
    -DPLUGIN_RESIDENT_APP_LOCALSTORAGESIZE="${RESIDENT_APP_LOCALSTORAGESIZE}" \
    -DPLUGIN_WEBKITBROWSER_LOCALSTORAGESIZE="${WEBKITBROWSER_LOCALSTORAGESIZE}" \
    -DPLUGIN_RESIDENT_APP_CLIENTIDENTIFIER="${RESIDENT_APP_CLIENTIDENTIFIER}" \
    -DPLUGIN_RESIDENT_APP_AUTOSTART="${RESIDENT_APP_AUTOSTART}" \
    -DPLUGIN_RESIDENT_APP_STARTURL="${RESIDENT_APP_STARTURL}" \
    -DPLUGIN_RESIDENT_APP_STARTUPORDER="${RESIDENT_APP_STARTUPORDER}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_CLIENTIDENTIFIER="${SEARCH_AND_DISCOVERY_APP_CLIENTIDENTIFIER}" \
    -DPLUGIN_WEBKITBROWSER_CLIENTIDENTIFIER="${WEBKITBROWSER_CLIENTIDENTIFIER}" \
    -DPLUGIN_HTML_APP_CLIENTIDENTIFIER="${HTML_APP_CLIENTIDENTIFIER}" \
    -DPLUGIN_LIGHTNING_APP_CLIENTIDENTIFIER="${LIGHTNING_APP_CLIENTIDENTIFIER}" \
    -DPLUGIN_JSPP_CLIENTIDENTIFIER="${JSPP_CLIENTIDENTIFIER}" \
    -DPLUGIN_HTML_APP_LOCALSTORAGE="${HTML_APP_LOCALSTORAGE}" \
    -DPLUGIN_HTML_APP_COOKIESTORAGE="${HTML_APP_LOCALSTORAGE}" \
    -DPLUGIN_LIGHTNING_APP_LOCALSTORAGE="${LIGHTNING_APP_LOCALSTORAGE}" \
    -DPLUGIN_LIGHTNING_APP_COOKIESTORAGE="${LIGHTNING_APP_LOCALSTORAGE}" \
    -DPLUGIN_JSPP_LOCALSTORAGE="${JSPP_LOCALSTORAGE}" \
    -DPLUGIN_JSPP_COOKIESTORAGE="${JSPP_LOCALSTORAGE}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_LOCALSTORAGE="${SEARCH_AND_DISCOVERY_APP_LOCALSTORAGE}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_COOKIESTORAGE="${SEARCH_AND_DISCOVERY_APP_LOCALSTORAGE}" \
    -DPLUGIN_RESIDENT_APP_LOCALSTORAGE="${RESIDENT_APP_LOCALSTORAGE}" \
    -DPLUGIN_RESIDENT_APP_COOKIESTORAGE="${RESIDENT_APP_LOCALSTORAGE}" \
    -DPLUGIN_WEBKITBROWSER_DISKCACHEDIR="${WEBKITBROWSER_DISKCACHEDIR}" \
    -DPLUGIN_RESIDENT_APP_DISKCACHEDIR="${RESIDENT_APP_DISKCACHEDIR}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_DISKCACHEDIR="${SEARCH_AND_DISCOVERY_APP_DISKCACHEDIR}" \
    -DPLUGIN_LIGHTNING_APP_DISKCACHEDIR="${LIGHTNING_APP_DISKCACHEDIR}" \
    -DPLUGIN_JSPP_DISKCACHEDIR="${JSPP_DISKCACHEDIR}" \
    -DPLUGIN_HTML_APP_DISKCACHEDIR="${HTML_APP_DISKCACHEDIR}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_SECURE="${SEARCH_AND_DISCOVERY_APP_SECURE}" \
    -DPLUGIN_RESIDENT_APP_SECURE="${RESIDENT_APP_SECURE}" \
    -DPLUGIN_HTML_APP_SECURE="${HTML_APP_SECURE}" \
    -DPLUGIN_LIGHTNING_APP_SECURE="${LIGHTNING_APP_SECURE}" \
    -DPLUGIN_JSPP_SECURE="${JSPP_SECURE}" \
    -DPLUGIN_WEBKITBROWSER_SECURE="${WEBKITBROWSER_SECURE}" \
    -DPLUGIN_HTML_APP_PERSISTENTPATHPOSTFIX="${HTML_APP_PERSISTENTPATHPOSTFIX}" \
    -DPLUGIN_LIGHTNING_APP_PERSISTENTPATHPOSTFIX="${LIGHTNING_APP_PERSISTENTPATHPOSTFIX}" \
    -DPLUGIN_JSPP_PERSISTENTPATHPOSTFIX="${JSPP_PERSISTENTPATHPOSTFIX}" \
    -DPLUGIN_RESIDENT_APP_PERSISTENTPATHPOSTFIX="${RESIDENT_APP_PERSISTENTPATHPOSTFIX}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_PERSISTENTPATHPOSTFIX="${SEARCH_AND_DISCOVERY_APP_PERSISTENTPATHPOSTFIX}" \
    -DPLUGIN_WEBKITBROWSER_PERSISTENTPATHPOSTFIX="${WEBKITBROWSER_PERSISTENTPATHPOSTFIX}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_MEMORYPRESSURE_WEBPROCESS_SETTINGS_LIMIT="${SEARCH_AND_DISCOVERY_APP_MEMORYPRESSURE_WEBPROCESSLIMIT}" \
    -DPLUGIN_RESIDENT_APP_MEMORYPRESSURE_WEBPROCESS_SETTINGS_LIMIT="${RESIDENT_APP_MEMORYPRESSURE_WEBPROCESSLIMIT}" \
    -DPLUGIN_HTML_APP_MEMORYPRESSURE_WEBPROCESS_SETTINGS_LIMIT="${HTML_APP_MEMORYPRESSURE_WEBPROCESSLIMIT}" \
    -DPLUGIN_LIGHTNING_APP_MEMORYPRESSURE_WEBPROCESS_SETTINGS_LIMIT="${LIGHTNING_APP_MEMORYPRESSURE_WEBPROCESSLIMIT}" \
    -DPLUGIN_HTML_APP_COMPOSITOR="${HTML_APP_COMPOSITOR}" \
    -DPLUGIN_LIGHTNING_APP_COMPOSITOR="${LIGHTNING_APP_COMPOSITOR}" \
    -DPLUGIN_JSPP_MEMORYPRESSURE_WEBPROCESS_SETTINGS_LIMIT="${JSPP_MEMORYPRESSURE_WEBPROCESSLIMIT}" \
    -DPLUGIN_JSPP_STARTURL="${JSPP_STARTURL}" \
    -DPLUGIN_JSPP_DISKCACHE="${JSPP_DISKCACHE}" \
    -DPLUGIN_JSPP_WEBINSPECTOR_ADDRESS="${JSPP_WEBINSPECTOR_ADDRESS}" \
    -DPLUGIN_JSPP_LOCALSTORAGE_ENABLE="${JSPP_LOCALSTORAGE_ENABLE}" \
"

FILES_SOLIBSDEV = ""
FILES:${PN} += "${libdir}/wpeframework/plugins/*.so ${libdir}/*.so ${datadir}/WPEFramework/*"
FILES:${PN}-dbg += "${datadir}/WPEFramework/WebKitBrowser/.debug"

INSANE_SKIP:${PN} += "libdir staticdev dev-so"
INSANE_SKIP:${PN}-dbg += "libdir"

PV = "1.1.30"
PR = "r0"
PACKAGE_ARCH = "${MIDDLEWARE_ARCH}"
