name: RDK-E Middleware Change Request
description: Change Request for RDK-E Middleware
title: "<JIRA TICKET>:<Ticket Title> "
labels: ["MW Change Request"]
body:
  - type: markdown
    attributes:
      value: |
        Change Request for RDK-E Middleware
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the feature or bug ticket
      placeholder: Describe the changes you are bringing
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any other relevant information
    validations:
      required: false
  
  - type: markdown
    attributes:
      value: |
        ---
        ## Definition of Done (DoD)
        Please select the status and provide details for each item below.

  # --- DoD Item 1 ---
  - type: dropdown
    id: dod-status-1
    attributes:
      label: 1. Middleware component tags with changelog
      options:
        - "Yes"
        - "No"
        - "N/A"
    validations:
      required: true
  - type: input
    id: dod-details-1
    attributes:
      label: Details for Item 1
      placeholder: "Link e.g. https://github.com/rdk-e/netmonitor/blob/1.4.0/CHANGELOG.md"

  # --- DoD Item 2 ---
  - type: dropdown
    id: dod-status-2
    attributes:
      label: 2. Impact on Devices (STBs, TVs)
      options:
        - "Yes"
        - "No"
        - "N/A"
    validations:
      required: true
  - type: input
    id: dod-details-2
    attributes:
      label: Details for Item 2
      placeholder: "Notes on Realtek, Broadcom, Amlogic, MediaTek..."

  # --- DoD Item 3 ---
  - type: dropdown
    id: dod-status-3
    attributes:
      label: 3. Dependent components
      options:
        - "Yes"
        - "No"
        - "N/A"
    validations:
      required: true
  - type: input
    id: dod-details-3
    attributes:
      label: Details for Item 3
      description: "If a feature involves more than one component changes, link the dependent component release task ticket clarifying the dependency"

  # --- DoD Item 4 ---
  - type: dropdown
    id: dod-status-4
    attributes:
      label: 4. Layer tags
      options:
        - "Yes"
        - "No"
        - "N/A"
    validations:
      required: true
  - type: input
    id: dod-details-4
    attributes:
      label: Details for Item 4
      description: "Tags released for OSS/OE repos, Layer release, product repo, build-support, RDKE config into middleware manifest"
      placeholder: "e.g: https://github.com/rdk-e/meta-image-support/blob/4.1.1/CHANGELOG.md"

  # --- DoD Item 5 ---
  - type: dropdown
    id: dod-status-5
    attributes:
      label: 5. Do Widgets Need Publishing
      options:
        - "Yes"
        - "No"
        - "N/A"
    validations:
      required: true
  - type: input
    id: dod-details-5
    attributes:
      label: Details for Item 5

  # --- DoD Item 6 ---
  - type: dropdown
    id: dod-status-6
    attributes:
      label: 6. Copilot review Done
      options:
        - "Yes"
        - "No"
        - "N/A"
    validations:
      required: true
  - type: input
    id: dod-details-6
    attributes:
      label: Details for Item 6