name: RDK-E Middleware Change Request
description: Change Request for RDK-E Middleware
title: "<JIRA TICKET>:<Ticket Title> "
labels: ["MW Change Request"]
body:
  - type: markdown
    attributes:
      value: |
        Change Request for RDK-E Middleware
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the feature or bug ticket
      placeholder: Describe the changes you are bringing
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any other relevant information
    validations:
      required: false
  
  - type: markdown
    attributes:
      value: |
        ---
        ## Definition of Done (DoD)
        
  # --- Pair 1 ---
  - type: checkboxes
    id: dod-1
    attributes:
      label: " "
      options:
        - label: Middleware component tags with changelog
  - type: input
    id: dod-1-details
    attributes:
      label: " "
      placeholder: https://github.com/rdk-e/netmonitor/blob/1.4.0/CHANGELOG.md
    validations:
      required: false

  # --- Pair 2 ---
  - type: checkboxes
    id: dod-2
    attributes:
      label: " "
      options:
        - label: Impact on Devices (STBs, TVs)
  - type: input
    id: dod-2-details
    attributes:
      label: " "
      placeholder: Notes on Realtek, Broadcom, Amlogic, MediaTek...
    validations:
      required: false

  # --- Pair 3 ---
  - type: checkboxes
    id: dod-3
    attributes:
      label: " "
      options:
        - label: Dependent components
  - type: input
    id: dod-3-details
    attributes:
      label: " "
      placeholder: Link dependent component release task if applicable
    validations:
      required: false

  # --- Pair 4 ---
  - type: checkboxes
    id: dod-4
    attributes:
      label: " "
      options:
        - label: Layer tags
  - type: input
    id: dod-4-details
    attributes:
      label: " "
      placeholder: e.g. https://github.com/rdk-e/meta-image-support/blob/4.1.1/CHANGELOG.md
    validations:
      required: false

  # --- Pair 5 ---
  - type: checkboxes
    id: dod-5
    attributes:
      label: " "
      options:
        - label: Do Widgets Need Publishing
  - type: input
    id: dod-5-details
    attributes:
      label: " "
      placeholder: Provide context if widgets are involved
    validations:
      required: false

  # --- Pair 6 ---
  - type: checkboxes
    id: dod-6
    attributes:
      label: " "
      options:
        - label: Copilot review Done
  - type: input
    id: dod-6-details
    attributes:
      label: " "
      placeholder: Any comments on the review
    validations:
      required: false