name: RDK-E Middleware Change Request
description: Change Request for RDK-E Middleware
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Change Request for RDK-E Middleware
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the feature or bug ticket
      placeholder: Describe the feature you'd like to see
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution and how it addresses the problem
      placeholder: How would you solve this?
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any other relevant information
    validations:
      required: false
  
  - type: markdown
    attributes:
      value: |
        ---
        ## Definition of Done (DoD)
        
        Update the status and details for each item as you work on this feature.
  
  - type: textarea
    id: dod-checklist
    attributes:
      label: Definition of Done Checklist
      description: Track progress on completion criteria. Update status and add details as you progress.
      value: |
        | Status | DoD Item | Details |
        |--------|----------|---------|
        | ⬜ Not Started | Middleware component tags with changelog | https://github.com/rdk-e/netmonitor/blob/1.4.0/CHANGELOG.md <br> |
        | ⬜ Not Started | Impact on Devices - STBs (Realtek, Broadcom), TVs (Amlogic, MediaTek) |  |
        | ⬜ Not Started | Dependent components	 | If a feature involves more than one component changes, link the dependent component release task ticket clarifying the dependency |
        | ⬜ Not Started | Layer tags | Tags released for OSS/OE repos, Layer release, product repo, build-support, RDKE config into middleware manifest <br> eg: https://github.com/rdk-e/meta-image-support/blob/4.1.1/CHANGELOG.md <br> |
        | ⬜ Not Started | Do Widgets Need Publishing  | |
        | ⬜ Not Started | Copilot review Done | |
        **Status options:** ⬜ Not Started | ✅ Done | ➖ Not Applicable
    validations:
      required: true
