# /media/apps/perf.conf
METRICS="syscpu,proccpu,cpu+"
SCENARIO="boot"
PROCESSES="syslog-ng|systemd-journal|logrotate|systemd-cat|WPEFramework|telemetry2_0"
DEVICE="mmcblk0p3"
INTERVAL=5
ITERATIONS=120
