# Configuration values in this file may change dynamically via TR-181 parameters.
makestep 1.0 3
server global-bootstrap-time1.xfinity.com iburst minpoll 10 maxpoll 12
server global-bootstrap-time2.xfinity.com iburst minpoll 10 maxpoll 12
