name: Build Health Check - Merge Issue PRs
on:
  workflow_dispatch:
    inputs:
      issueURL:
        description: 'Please enter the Issue URL, eg: https://github.com/rdk-e/meta-rdk-video/issues/2407'
        required: true
        type: string

jobs:
  Merge_prs:
    uses: rdkcentral/build_tools_workflows/.github/workflows/bhc_issue_merge_all_prs.yml@develop
    with:
      issueURL: ${{ github.event.inputs.issueURL }}
    secrets:
      RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}
